FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive


SHELL ["/bin/bash", "-c"] 

USER root

RUN apt-get update \
    && apt-get install -y \
    cmake \
    git \
    python3 \
    python3-pip \
    libusb-1.0-0 \
    libffi-dev \
    pkg-config

ARG MICROPYTHON_DIR=/micropython
ARG MICROPYTHON_VERSION=v1.19.1

RUN git clone -b ${MICROPYTHON_VERSION} https://github.com/micropython/micropython.git ${MICROPYTHON_DIR}

WORKDIR ${MICROPYTHON_DIR}

# build vanilla first to re-use docker layer
# RUN source tools/ci.sh && ci_esp32_build

COPY src/midicontroller ${MICROPYTHON_DIR}/ports/unix/modules/midicontroller
COPY src/wifi.py ${MICROPYTHON_DIR}/ports/unix/modules/
# COPY src/main.py ${MICROPYTHON_DIR}/ports/unix/modules/boot.py

# RUN source tools/ci.sh && ci_unix_standard_build
WORKDIR ${MICROPYTHON_DIR}/ports/unix
RUN make submodules && make 
